{{- $licenseKey := include "newrelic-logging.licenseKey" . -}}
{{- if $licenseKey }}
apiVersion: v1
kind: Secret
metadata:
  labels: {{ include "newrelic-logging.labels" . | indent 4 }}
  name: {{ template "newrelic-logging.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  license: {{ $licenseKey | b64enc }}
{{- end }}
