{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: {{ template "newrelic-logging.name" . }}
    chart: {{ template "newrelic-logging.chart" . }}
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
  name: {{ template "newrelic-logging.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end -}}
